### ISSUE TITLE
Adding game specific tests

### ISSUE THREAD

**Issue by jpd002** [unknownbrackets/ps2autotests#2] opened 2015-04-27 04:04 UTC
What would be the best way to go for adding game specific tests to the test suite? I'm talking about adding tests like this one: https://github.com/jpd002/Play-/blob/master/tools/VuTest/TriAceTest.cpp 

The idea is just to test specific scenarios that we encounter while developing the emulator. pspautotests doesn't seem to have anything like that, so I was wondering if that would be something that would belong to this test suite.

**Comment by unknownbrackets** [comment] 2015-04-27 04:33
Well, I don't think it's a bad idea.  I actually have a few local pspautotests that are game specific (mostly savedata, video, or music related), but generally I've tried to make them "generic".  For example, [this one](https://github.com/hrydgard/pspautotests/blob/master/tests/cpu/vfpu/vregs.cpp) covers a regcache issue that was really hard to reproduce outside just this one game (some Tekken.)

But in some cases, there will be specific tricks, especially with this bare-metal access.  I think it will be much more common to want game-specific tests than on the PSP.

My only real concern I have is copyright.  As long as the tests don't encourage anything that could be copyright violation (e.g. of the game's code) it seems like something that makes sense.  Unfortunately, I don't rightly know where the line is (I'm not a lawyer and I've never even played one on TV.)

Not sure about organization either.  Such a test might be `tests/game/vu/triace.elf`?  Or `tests/vu/game/triace.elf`?  Depends how common they might be, I guess.

-[Unknown]

**Comment by jpd002** [comment] 2015-04-28 06:58
Yeah, you're right about the copyright issue, I don't really know where to trace the line either. But for this particular instance, it's not exposing the whole decryption/decompression algorithm, so, it's kinda useless on its own. So, maybe it would be ok to have very specific tests like this one in there.

I think it makes more sense to put the test in `tests/vu/game` for now, since all the facilities to generate VU code is already in `tests/vu`.

**Comment by unknownbrackets** [comment] 2015-04-28 07:16
Yeah, that makes sense.  I agree about the utilities being nearby, so that folder structure makes more sense.

Anyway, I think tests of specific sequences of immediate load usage and register thrashing make sense in any case.

-[Unknown]

**Comment by unknownbrackets** [comment] 2015-05-12 04:57
I'm going to close this now, since #4 is merged and the bridge of game-specific tests has been crossed.  Thanks.

-[Unknown]

**Closed as completed by unknownbrackets** 2015-05-12 04:57 UTC
